- name: Copying the rsyslog config 
  ansible.builtin.template:
    src: rsyslog.conf  
    dest: /etc/rsyslog.d/rsyslog.conf

- name: Restarting rsyslog  
  systemd:
    name: rsyslog 
    state: restarted
    enabled: yes
    daemon_reload: yes