- name: Creating {{APPUSER}}
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop app user
  register: USERINFO

- name: Printing the variable
  ansible.builtin.debug:
     msg: Value of the OUT is {{USERINFO}}

- name: Installing boto3 and botocore as preReq for SSH Lookup
  ansible.builtin.pip:
    name: 
      - botocore
      - boto3
    executable: pip3