- name: Performing {{COMPONENT}} Cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent
  ignore_errors: yes

- name: Create a App Directory 
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}/
    state: directory
    mode: '0755'
  become_user: "{{APPUSER}}"

- name: Download and extracting {{COMPONENT}} from Nexus 
  ansible.builtin.unarchive:
    src: http://172.31.87.144:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    remote_src: yes  